The most convenient method to prepare the |flash_section_content_evk| board for flashing is to let the Exploration Tool Application
automatically download the latest binary file from our `developer page <https://developer.acconeer.com/>`_.
If you want to flash a binary that you have locally on your computer; that is also possible.

Depending on how you installed in :ref:`installation-and-setup`, start Exploration Tool by either

* Double-clicking the ``run_app`` script,
* Running the command ``python -m acconeer.exptool.app`` in your terminal.

Then get started by pressing the **Flash** button in Exploration Tool and you will be guided through the flashing process.

.. figure:: /_static/et_flash_button_highlight.gif
   :align: center
   :width: 100%
